### ISSUE TITLE
Error Not Found

### ISSUE THREAD

**Issue by PascalBru** [huwan/urlwatch-actions-demo#1]
A very good example for the use of actions.
My repo is https://github.com/PascalBru/test-urlwatch but I always get an error Not Found for the cache.db any idea what's wrong?

**Comment by huwan** [comment]
GitHub renames the default branch from `master` to `main` in new repositories. The default branch of this repo is `master`, yours is `main`. So you need to change the branch name in the main.yaml (L6 and L44) to `main`.

PS: I adjust the retention period from default 90 days to 1 day to delete old artifacts timely because the storage is limit (512MB), please see latest commit.

**Comment by PascalBru** [comment]
THX that was so easy, but I haven't seen.
